import React from "react";
import Head from "next/head";
import { PostCard } from "@/components";
import { getPostsBasic } from "@/services";

export default function Events({ posts }) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="event page-marker">
        {posts.map((post, index) => (
          <PostCard post={post.node} key={index} />
        ))}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const posts = (await getPostsBasic()) || [];
  return {
    props: { posts },
  };
}
