import Head from "next/head";
import { PostCard, Categories, PostWidget } from "@/components";
// import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

const posts = [
  { title: "React Testing", excerpt: "Learn React Testing" },
  { title: "Bootstrap Testing", excerpt: "Learn Bootstrap Testing" },
];
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <div>
          <div className="row">
            {posts.map((post) => (
              <PostCard post={post} key={post.title} />
            ))}
            {/* see video at 30:35 for setup divs*/}
          </div>
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg-sticky relative top-8">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </>
  );
}
