import React from "react";
import Head from "next/head";
import styles from "@/styles/Video.module.css";

const Videos = () => {
  return (
    <>
      <Head>
        <title>Videos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="video-page-marker">
        <h2>Recent Messages</h2>
        <div className={styles.outerContainer}>
          <div className={styles.iframeContainer}>
            <iframe
              // in channel id you must change UC2KX... to UU2KX...
              src="https://www.youtube-nocookie.com/embed?listType=playlist&list=UU2KX862afQKX4qc6ryGKQVA&rel=0&index=1"
              title="YouTube video player"
              allowFullScreen
              className="rounded"
            ></iframe>
          </div>
        </div>
        <div className={styles.outerContainer}>
          <div className={styles.iframeContainer}>
            <iframe
              src="https://www.youtube-nocookie.com/embed?listType=playlist&list=UU2KX862afQKX4qc6ryGKQVA&rel=0&index=2"
              title="YouTube video player"
              allowFullScreen
              className="rounded"
            ></iframe>
          </div>
        </div>
        <div className={styles.outerContainer}>
          <div className={styles.iframeContainer}>
            <iframe
              src="https://www.youtube-nocookie.com/embed?listType=playlist&list=UU2KX862afQKX4qc6ryGKQVA&rel=0&index=3"
              title="YouTube video player"
              allowFullScreen
              className="rounded"
            ></iframe>
          </div>
        </div>
      </div>
    </>
  );
};

export default Videos;
